export const API_COMMENT_TEST_DATA = [
    {
       "kind":"Listing",
       "data":{
          "modhash":"",
          "dist":1,
          "children":[
             {
                "kind":"t3",
                "data":{
                   "approved_at_utc":null,
                   "subreddit":"nhaa",
                   "selftext":"",
                   "user_reports":[
                      
                   ],
                   "saved":false,
                   "mod_reason_title":null,
                   "gilded":0,
                   "clicked":false,
                   "title":"iNtErEsSaNtE",
                   "link_flair_richtext":[
                      {
                         "e":"text",
                         "t":"MEME"
                      }
                   ],
                   "subreddit_name_prefixed":"r/nhaa",
                   "hidden":false,
                   "pwls":6,
                   "link_flair_css_class":"",
                   "downs":0,
                   "thumbnail_height":110,
                   "top_awarded_type":null,
                   "parent_whitelist_status":"all_ads",
                   "hide_score":false,
                   "name":"t3_j62yd8",
                   "quarantine":false,
                   "link_flair_text_color":"light",
                   "upvote_ratio":0.98,
                   "author_flair_background_color":null,
                   "subreddit_type":"public",
                   "ups":204,
                   "total_awards_received":0,
                   "media_embed":{
                      
                   },
                   "thumbnail_width":140,
                   "author_flair_template_id":null,
                   "is_original_content":false,
                   "author_fullname":"t2_7u2v3fjb",
                   "secure_media":null,
                   "is_reddit_media_domain":true,
                   "is_meta":false,
                   "category":null,
                   "secure_media_embed":{
                      
                   },
                   "link_flair_text":"MEME",
                   "can_mod_post":false,
                   "score":204,
                   "approved_by":null,
                   "author_premium":false,
                   "thumbnail":"https://b.thumbs.redditmedia.com/5p7NFXELgmmoFs6mNSNtDNfrkcZHzlERPZMa7STViWk.jpg",
                   "edited":false,
                   "author_flair_css_class":null,
                   "author_flair_richtext":[
                      
                   ],
                   "gildings":{
                      
                   },
                   "post_hint":"image",
                   "content_categories":null,
                   "is_self":false,
                   "mod_note":null,
                   "created":1602010443.0,
                   "link_flair_type":"richtext",
                   "wls":6,
                   "removed_by_category":null,
                   "banned_by":null,
                   "author_flair_type":"text",
                   "domain":"i.redd.it",
                   "allow_live_comments":false,
                   "selftext_html":null,
                   "likes":null,
                   "suggested_sort":null,
                   "banned_at_utc":null,
                   "url_overridden_by_dest":"https://i.redd.it/ot5sj02eggr51.jpg",
                   "view_count":null,
                   "archived":false,
                   "no_follow":false,
                   "is_crosspostable":false,
                   "pinned":false,
                   "over_18":false,
                   "preview":{
                      "images":[
                         {
                            "source":{
                               "url":"https://preview.redd.it/ot5sj02eggr51.jpg?auto=webp&amp;s=d395211eb5accdf37f30b19c8ddaaf8322ce130c",
                               "width":720,
                               "height":566
                            },
                            "resolutions":[
                               {
                                  "url":"https://preview.redd.it/ot5sj02eggr51.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=1ceafe3553239fc880f61d0ec3e9cbbf6cc2ddaf",
                                  "width":108,
                                  "height":84
                               },
                               {
                                  "url":"https://preview.redd.it/ot5sj02eggr51.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=41125d2f03ef20b0be2549932367e40b50d31ca6",
                                  "width":216,
                                  "height":169
                               },
                               {
                                  "url":"https://preview.redd.it/ot5sj02eggr51.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=dfb9913005fc039295d5156840791fc0c2ab2e7c",
                                  "width":320,
                                  "height":251
                               },
                               {
                                  "url":"https://preview.redd.it/ot5sj02eggr51.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=049a166ee443d4076cda3ed841c010b07dd1b6dd",
                                  "width":640,
                                  "height":503
                               }
                            ],
                            "variants":{
                               
                            },
                            "id":"wx4kdc4YIdTwZ3WTSq7RAwM2g9rIt6SvdI33A0xjc50"
                         }
                      ],
                      "enabled":true
                   },
                   "all_awardings":[
                      
                   ],
                   "awarders":[
                      
                   ],
                   "media_only":false,
                   "link_flair_template_id":"cc3f2bcc-aecb-11e9-b329-0e18d1a68012",
                   "can_gild":false,
                   "spoiler":false,
                   "locked":false,
                   "author_flair_text":null,
                   "treatment_tags":[
                      
                   ],
                   "visited":false,
                   "removed_by":null,
                   "num_reports":null,
                   "distinguished":null,
                   "subreddit_id":"t5_qwpqj",
                   "mod_reason_by":null,
                   "removal_reason":null,
                   "link_flair_background_color":"#46d160",
                   "id":"j62yd8",
                   "is_robot_indexable":true,
                   "num_duplicates":0,
                   "report_reasons":null,
                   "author":"peaojedro0",
                   "discussion_type":null,
                   "num_comments":8,
                   "send_replies":true,
                   "media":null,
                   "contest_mode":false,
                   "author_patreon_flair":false,
                   "author_flair_text_color":null,
                   "permalink":"/r/nhaa/comments/j62yd8/interessante/",
                   "whitelist_status":"all_ads",
                   "stickied":false,
                   "url":"https://i.redd.it/ot5sj02eggr51.jpg",
                   "subreddit_subscribers":369832,
                   "created_utc":1601981643.0,
                   "num_crossposts":0,
                   "mod_reports":[
                      
                   ],
                   "is_video":false
                }
             }
          ],
          "after":null,
          "before":null
       }
    },
    {
       "kind":"Listing",
       "data":{
          "modhash":"",
          "dist":null,
          "children":[
             {
                "kind":"t1",
                "data":{
                   "total_awards_received":0,
                   "approved_at_utc":null,
                   "comment_type":null,
                   "awarders":[
                      
                   ],
                   "mod_reason_by":null,
                   "banned_by":null,
                   "ups":4,
                   "author_flair_type":"text",
                   "removal_reason":null,
                   "link_id":"t3_j62yd8",
                   "author_flair_template_id":null,
                   "likes":null,
                   "replies":"",
                   "user_reports":[
                      
                   ],
                   "saved":false,
                   "id":"g7w13ig",
                   "banned_at_utc":null,
                   "mod_reason_title":null,
                   "gilded":0,
                   "archived":false,
                   "no_follow":false,
                   "author":"nidderegunkerium",
                   "can_mod_post":false,
                   "send_replies":true,
                   "parent_id":"t3_j62yd8",
                   "score":4,
                   "author_fullname":"t2_887xqqip",
                   "report_reasons":null,
                   "approved_by":null,
                   "all_awardings":[
                      
                   ],
                   "subreddit_id":"t5_qwpqj",
                   "body":"Isso \u00e9 usar 100% do c\u00e9rebro",
                   "edited":false,
                   "downs":0,
                   "author_flair_css_class":null,
                   "is_submitter":false,
                   "collapsed":false,
                   "author_flair_richtext":[
                      
                   ],
                   "author_patreon_flair":false,
                   "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;Isso \u00e9 usar 100% do c\u00e9rebro&lt;/p&gt;\n&lt;/div&gt;",
                   "gildings":{
                      
                   },
                   "collapsed_reason":null,
                   "associated_award":null,
                   "stickied":false,
                   "author_premium":false,
                   "subreddit_type":"public",
                   "can_gild":true,
                   "top_awarded_type":null,
                   "author_flair_text_color":null,
                   "score_hidden":false,
                   "permalink":"/r/nhaa/comments/j62yd8/interessante/g7w13ig/",
                   "num_reports":null,
                   "locked":false,
                   "name":"t1_g7w13ig",
                   "created":1602017062.0,
                   "subreddit":"nhaa",
                   "author_flair_text":null,
                   "treatment_tags":[
                      
                   ],
                   "created_utc":1601988262.0,
                   "subreddit_name_prefixed":"r/nhaa",
                   "controversiality":0,
                   "depth":0,
                   "author_flair_background_color":null,
                   "collapsed_because_crowd_control":null,
                   "mod_reports":[
                      
                   ],
                   "mod_note":null,
                   "distinguished":null
                }
             },
             {
                "kind":"t1",
                "data":{
                   "total_awards_received":0,
                   "approved_at_utc":null,
                   "comment_type":null,
                   "awarders":[
                      
                   ],
                   "mod_reason_by":null,
                   "banned_by":null,
                   "ups":1,
                   "author_flair_type":"text",
                   "removal_reason":null,
                   "link_id":"t3_j62yd8",
                   "author_flair_template_id":null,
                   "likes":null,
                   "replies":"",
                   "user_reports":[
                      
                   ],
                   "saved":false,
                   "id":"g7w7cfo",
                   "banned_at_utc":null,
                   "mod_reason_title":null,
                   "gilded":0,
                   "archived":false,
                   "no_follow":true,
                   "author":"yo-landi__viSSer",
                   "can_mod_post":false,
                   "send_replies":true,
                   "parent_id":"t3_j62yd8",
                   "score":1,
                   "author_fullname":"t2_78mhpxso",
                   "report_reasons":null,
                   "approved_by":null,
                   "all_awardings":[
                      
                   ],
                   "subreddit_id":"t5_qwpqj",
                   "body":"cir\u00fargico",
                   "edited":false,
                   "downs":0,
                   "author_flair_css_class":null,
                   "is_submitter":false,
                   "collapsed":false,
                   "author_flair_richtext":[
                      
                   ],
                   "author_patreon_flair":false,
                   "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;cir\u00fargico&lt;/p&gt;\n&lt;/div&gt;",
                   "gildings":{
                      
                   },
                   "collapsed_reason":null,
                   "associated_award":null,
                   "stickied":false,
                   "author_premium":false,
                   "subreddit_type":"public",
                   "can_gild":true,
                   "top_awarded_type":null,
                   "author_flair_text_color":null,
                   "score_hidden":false,
                   "permalink":"/r/nhaa/comments/j62yd8/interessante/g7w7cfo/",
                   "num_reports":null,
                   "locked":false,
                   "name":"t1_g7w7cfo",
                   "created":1602021029.0,
                   "subreddit":"nhaa",
                   "author_flair_text":null,
                   "treatment_tags":[
                      
                   ],
                   "created_utc":1601992229.0,
                   "subreddit_name_prefixed":"r/nhaa",
                   "controversiality":0,
                   "depth":0,
                   "author_flair_background_color":null,
                   "collapsed_because_crowd_control":null,
                   "mod_reports":[
                      
                   ],
                   "mod_note":null,
                   "distinguished":null
                }
             },
             {
                "kind":"t1",
                "data":{
                   "total_awards_received":0,
                   "approved_at_utc":null,
                   "comment_type":null,
                   "awarders":[
                      
                   ],
                   "mod_reason_by":null,
                   "banned_by":null,
                   "ups":2,
                   "author_flair_type":"text",
                   "removal_reason":null,
                   "link_id":"t3_j62yd8",
                   "author_flair_template_id":null,
                   "likes":null,
                   "replies":{
                      "kind":"Listing",
                      "data":{
                         "modhash":"",
                         "dist":null,
                         "children":[
                            {
                               "kind":"t1",
                               "data":{
                                  "total_awards_received":0,
                                  "approved_at_utc":null,
                                  "comment_type":null,
                                  "awarders":[
                                     
                                  ],
                                  "mod_reason_by":null,
                                  "banned_by":null,
                                  "ups":2,
                                  "author_flair_type":"text",
                                  "removal_reason":null,
                                  "link_id":"t3_j62yd8",
                                  "author_flair_template_id":null,
                                  "likes":null,
                                  "replies":"",
                                  "user_reports":[
                                     
                                  ],
                                  "saved":false,
                                  "id":"g7vu0z0",
                                  "banned_at_utc":null,
                                  "mod_reason_title":null,
                                  "gilded":0,
                                  "archived":false,
                                  "no_follow":true,
                                  "author":"peaojedro0",
                                  "can_mod_post":false,
                                  "send_replies":true,
                                  "parent_id":"t1_g7vtt9k",
                                  "score":2,
                                  "author_fullname":"t2_7u2v3fjb",
                                  "report_reasons":null,
                                  "approved_by":null,
                                  "all_awardings":[
                                     
                                  ],
                                  "subreddit_id":"t5_qwpqj",
                                  "collapsed":false,
                                  "body":"DYDISLSLSKSJRKWNAKKS",
                                  "edited":false,
                                  "author_flair_css_class":null,
                                  "is_submitter":true,
                                  "downs":0,
                                  "author_flair_richtext":[
                                     
                                  ],
                                  "author_patreon_flair":false,
                                  "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;DYDISLSLSKSJRKWNAKKS&lt;/p&gt;\n&lt;/div&gt;",
                                  "gildings":{
                                     
                                  },
                                  "collapsed_reason":null,
                                  "associated_award":null,
                                  "stickied":false,
                                  "author_premium":false,
                                  "subreddit_type":"public",
                                  "can_gild":true,
                                  "top_awarded_type":null,
                                  "author_flair_text_color":null,
                                  "score_hidden":false,
                                  "permalink":"/r/nhaa/comments/j62yd8/interessante/g7vu0z0/",
                                  "num_reports":null,
                                  "locked":false,
                                  "name":"t1_g7vu0z0",
                                  "created":1602011142.0,
                                  "subreddit":"nhaa",
                                  "author_flair_text":null,
                                  "treatment_tags":[
                                     
                                  ],
                                  "created_utc":1601982342.0,
                                  "subreddit_name_prefixed":"r/nhaa",
                                  "controversiality":0,
                                  "depth":1,
                                  "author_flair_background_color":null,
                                  "collapsed_because_crowd_control":null,
                                  "mod_reports":[
                                     
                                  ],
                                  "mod_note":null,
                                  "distinguished":null
                               }
                            }
                         ],
                         "after":null,
                         "before":null
                      }
                   },
                   "user_reports":[
                      
                   ],
                   "saved":false,
                   "id":"g7vtt9k",
                   "banned_at_utc":null,
                   "mod_reason_title":null,
                   "gilded":0,
                   "archived":false,
                   "no_follow":true,
                   "author":"otakoburguessafado",
                   "can_mod_post":false,
                   "send_replies":true,
                   "parent_id":"t3_j62yd8",
                   "score":2,
                   "author_fullname":"t2_636b33fw",
                   "report_reasons":null,
                   "approved_by":null,
                   "all_awardings":[
                      
                   ],
                   "subreddit_id":"t5_qwpqj",
                   "body":"S\u00e1bio dms",
                   "edited":false,
                   "downs":0,
                   "author_flair_css_class":null,
                   "is_submitter":false,
                   "collapsed":false,
                   "author_flair_richtext":[
                      
                   ],
                   "author_patreon_flair":false,
                   "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;S\u00e1bio dms&lt;/p&gt;\n&lt;/div&gt;",
                   "gildings":{
                      
                   },
                   "collapsed_reason":null,
                   "associated_award":null,
                   "stickied":false,
                   "author_premium":false,
                   "subreddit_type":"public",
                   "can_gild":true,
                   "top_awarded_type":null,
                   "author_flair_text_color":null,
                   "score_hidden":false,
                   "permalink":"/r/nhaa/comments/j62yd8/interessante/g7vtt9k/",
                   "num_reports":null,
                   "locked":false,
                   "name":"t1_g7vtt9k",
                   "created":1602010921.0,
                   "subreddit":"nhaa",
                   "author_flair_text":null,
                   "treatment_tags":[
                      
                   ],
                   "created_utc":1601982121.0,
                   "subreddit_name_prefixed":"r/nhaa",
                   "controversiality":0,
                   "depth":0,
                   "author_flair_background_color":null,
                   "collapsed_because_crowd_control":null,
                   "mod_reports":[
                      
                   ],
                   "mod_note":null,
                   "distinguished":null
                }
             },
             {
                "kind":"t1",
                "data":{
                   "total_awards_received":0,
                   "approved_at_utc":null,
                   "comment_type":null,
                   "awarders":[
                      
                   ],
                   "mod_reason_by":null,
                   "banned_by":null,
                   "ups":2,
                   "author_flair_type":"text",
                   "removal_reason":null,
                   "link_id":"t3_j62yd8",
                   "author_flair_template_id":null,
                   "likes":null,
                   "replies":{
                      "kind":"Listing",
                      "data":{
                         "modhash":"",
                         "dist":null,
                         "children":[
                            {
                               "kind":"t1",
                               "data":{
                                  "total_awards_received":0,
                                  "approved_at_utc":null,
                                  "comment_type":null,
                                  "awarders":[
                                     
                                  ],
                                  "mod_reason_by":null,
                                  "banned_by":null,
                                  "ups":1,
                                  "author_flair_type":"text",
                                  "removal_reason":null,
                                  "link_id":"t3_j62yd8",
                                  "author_flair_template_id":null,
                                  "likes":null,
                                  "replies":{
                                     "kind":"Listing",
                                     "data":{
                                        "modhash":"",
                                        "dist":null,
                                        "children":[
                                           {
                                              "kind":"t1",
                                              "data":{
                                                 "total_awards_received":0,
                                                 "approved_at_utc":null,
                                                 "comment_type":null,
                                                 "awarders":[
                                                    
                                                 ],
                                                 "mod_reason_by":null,
                                                 "banned_by":null,
                                                 "ups":1,
                                                 "author_flair_type":"text",
                                                 "removal_reason":null,
                                                 "link_id":"t3_j62yd8",
                                                 "author_flair_template_id":null,
                                                 "likes":null,
                                                 "replies":{
                                                    "kind":"Listing",
                                                    "data":{
                                                       "modhash":"",
                                                       "dist":null,
                                                       "children":[
                                                          {
                                                             "kind":"t1",
                                                             "data":{
                                                                "total_awards_received":0,
                                                                "approved_at_utc":null,
                                                                "comment_type":null,
                                                                "awarders":[
                                                                   
                                                                ],
                                                                "mod_reason_by":null,
                                                                "banned_by":null,
                                                                "ups":1,
                                                                "author_flair_type":"text",
                                                                "removal_reason":null,
                                                                "link_id":"t3_j62yd8",
                                                                "author_flair_template_id":null,
                                                                "likes":null,
                                                                "replies":"",
                                                                "user_reports":[
                                                                   
                                                                ],
                                                                "saved":false,
                                                                "id":"g7w7g87",
                                                                "banned_at_utc":null,
                                                                "mod_reason_title":null,
                                                                "gilded":0,
                                                                "archived":false,
                                                                "no_follow":true,
                                                                "author":"peaojedro0",
                                                                "can_mod_post":false,
                                                                "send_replies":true,
                                                                "parent_id":"t1_g7w7bc3",
                                                                "score":1,
                                                                "author_fullname":"t2_7u2v3fjb",
                                                                "report_reasons":null,
                                                                "approved_by":null,
                                                                "all_awardings":[
                                                                   
                                                                ],
                                                                "subreddit_id":"t5_qwpqj",
                                                                "body":"Will",
                                                                "edited":false,
                                                                "downs":0,
                                                                "author_flair_css_class":null,
                                                                "is_submitter":true,
                                                                "collapsed":false,
                                                                "author_flair_richtext":[
                                                                   
                                                                ],
                                                                "author_patreon_flair":false,
                                                                "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;Will&lt;/p&gt;\n&lt;/div&gt;",
                                                                "gildings":{
                                                                   
                                                                },
                                                                "collapsed_reason":null,
                                                                "associated_award":null,
                                                                "stickied":false,
                                                                "author_premium":false,
                                                                "subreddit_type":"public",
                                                                "can_gild":true,
                                                                "top_awarded_type":null,
                                                                "author_flair_text_color":null,
                                                                "score_hidden":false,
                                                                "permalink":"/r/nhaa/comments/j62yd8/interessante/g7w7g87/",
                                                                "num_reports":null,
                                                                "locked":false,
                                                                "name":"t1_g7w7g87",
                                                                "created":1602021091.0,
                                                                "subreddit":"nhaa",
                                                                "author_flair_text":null,
                                                                "treatment_tags":[
                                                                   
                                                                ],
                                                                "created_utc":1601992291.0,
                                                                "subreddit_name_prefixed":"r/nhaa",
                                                                "controversiality":0,
                                                                "depth":3,
                                                                "author_flair_background_color":null,
                                                                "collapsed_because_crowd_control":null,
                                                                "mod_reports":[
                                                                   
                                                                ],
                                                                "mod_note":null,
                                                                "distinguished":null
                                                             }
                                                          }
                                                       ],
                                                       "after":null,
                                                       "before":null
                                                    }
                                                 },
                                                 "user_reports":[
                                                    
                                                 ],
                                                 "saved":false,
                                                 "id":"g7w7bc3",
                                                 "banned_at_utc":null,
                                                 "mod_reason_title":null,
                                                 "gilded":0,
                                                 "archived":false,
                                                 "no_follow":true,
                                                 "author":"Um_garoto_aleatorio",
                                                 "can_mod_post":false,
                                                 "created_utc":1601992212.0,
                                                 "send_replies":true,
                                                 "parent_id":"t1_g7vzl76",
                                                 "score":1,
                                                 "author_fullname":"t2_79u4vkhx",
                                                 "report_reasons":null,
                                                 "approved_by":null,
                                                 "all_awardings":[
                                                    
                                                 ],
                                                 "subreddit_id":"t5_qwpqj",
                                                 "body":"Mas \u00e9 s\u00f3 ele se virar para o mar, ent tudo estar\u00e1 invertido",
                                                 "edited":false,
                                                 "author_flair_css_class":null,
                                                 "is_submitter":false,
                                                 "downs":0,
                                                 "author_flair_richtext":[
                                                    
                                                 ],
                                                 "author_patreon_flair":false,
                                                 "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;Mas \u00e9 s\u00f3 ele se virar para o mar, ent tudo estar\u00e1 invertido&lt;/p&gt;\n&lt;/div&gt;",
                                                 "gildings":{
                                                    
                                                 },
                                                 "collapsed_reason":null,
                                                 "associated_award":null,
                                                 "stickied":false,
                                                 "author_premium":false,
                                                 "subreddit_type":"public",
                                                 "can_gild":true,
                                                 "top_awarded_type":null,
                                                 "author_flair_text_color":null,
                                                 "score_hidden":false,
                                                 "permalink":"/r/nhaa/comments/j62yd8/interessante/g7w7bc3/",
                                                 "num_reports":null,
                                                 "locked":false,
                                                 "name":"t1_g7w7bc3",
                                                 "created":1602021012.0,
                                                 "subreddit":"nhaa",
                                                 "author_flair_text":null,
                                                 "treatment_tags":[
                                                    
                                                 ],
                                                 "collapsed":false,
                                                 "subreddit_name_prefixed":"r/nhaa",
                                                 "controversiality":0,
                                                 "depth":2,
                                                 "author_flair_background_color":null,
                                                 "collapsed_because_crowd_control":null,
                                                 "mod_reports":[
                                                    
                                                 ],
                                                 "mod_note":null,
                                                 "distinguished":null
                                              }
                                           }
                                        ],
                                        "after":null,
                                        "before":null
                                     }
                                  },
                                  "user_reports":[
                                     
                                  ],
                                  "saved":false,
                                  "id":"g7vzl76",
                                  "banned_at_utc":null,
                                  "mod_reason_title":null,
                                  "gilded":0,
                                  "archived":false,
                                  "no_follow":true,
                                  "author":"peaojedro0",
                                  "can_mod_post":false,
                                  "send_replies":true,
                                  "parent_id":"t1_g7vzjk3",
                                  "score":1,
                                  "author_fullname":"t2_7u2v3fjb",
                                  "report_reasons":null,
                                  "approved_by":null,
                                  "all_awardings":[
                                     
                                  ],
                                  "subreddit_id":"t5_qwpqj",
                                  "collapsed":false,
                                  "body":"\u00e9 s\u00f3 usar o seu breins",
                                  "edited":false,
                                  "author_flair_css_class":null,
                                  "is_submitter":true,
                                  "downs":0,
                                  "author_flair_richtext":[
                                     
                                  ],
                                  "author_patreon_flair":false,
                                  "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;\u00e9 s\u00f3 usar o seu breins&lt;/p&gt;\n&lt;/div&gt;",
                                  "gildings":{
                                     
                                  },
                                  "collapsed_reason":null,
                                  "associated_award":null,
                                  "stickied":false,
                                  "author_premium":false,
                                  "subreddit_type":"public",
                                  "can_gild":true,
                                  "top_awarded_type":null,
                                  "author_flair_text_color":null,
                                  "score_hidden":false,
                                  "permalink":"/r/nhaa/comments/j62yd8/interessante/g7vzl76/",
                                  "num_reports":null,
                                  "locked":false,
                                  "name":"t1_g7vzl76",
                                  "created":1602015976.0,
                                  "subreddit":"nhaa",
                                  "author_flair_text":null,
                                  "treatment_tags":[
                                     
                                  ],
                                  "created_utc":1601987176.0,
                                  "subreddit_name_prefixed":"r/nhaa",
                                  "controversiality":0,
                                  "depth":1,
                                  "author_flair_background_color":null,
                                  "collapsed_because_crowd_control":null,
                                  "mod_reports":[
                                     
                                  ],
                                  "mod_note":null,
                                  "distinguished":null
                               }
                            }
                         ],
                         "after":null,
                         "before":null
                      }
                   },
                   "user_reports":[
                      
                   ],
                   "saved":false,
                   "id":"g7vzjk3",
                   "banned_at_utc":null,
                   "mod_reason_title":null,
                   "gilded":0,
                   "archived":false,
                   "no_follow":true,
                   "author":"x_achiles_x",
                   "can_mod_post":false,
                   "send_replies":true,
                   "parent_id":"t3_j62yd8",
                   "score":2,
                   "author_fullname":"t2_7pbgtpo7",
                   "report_reasons":null,
                   "approved_by":null,
                   "all_awardings":[
                      
                   ],
                   "subreddit_id":"t5_qwpqj",
                   "body":"Muita sabedoria",
                   "edited":false,
                   "downs":0,
                   "author_flair_css_class":null,
                   "is_submitter":false,
                   "collapsed":false,
                   "author_flair_richtext":[
                      
                   ],
                   "author_patreon_flair":false,
                   "body_html":"&lt;div class=\"md\"&gt;&lt;p&gt;Muita sabedoria&lt;/p&gt;\n&lt;/div&gt;",
                   "gildings":{
                      
                   },
                   "collapsed_reason":null,
                   "associated_award":null,
                   "stickied":false,
                   "author_premium":false,
                   "subreddit_type":"public",
                   "can_gild":true,
                   "top_awarded_type":null,
                   "author_flair_text_color":null,
                   "score_hidden":false,
                   "permalink":"/r/nhaa/comments/j62yd8/interessante/g7vzjk3/",
                   "num_reports":null,
                   "locked":false,
                   "name":"t1_g7vzjk3",
                   "created":1602015941.0,
                   "subreddit":"nhaa",
                   "author_flair_text":null,
                   "treatment_tags":[
                      
                   ],
                   "created_utc":1601987141.0,
                   "subreddit_name_prefixed":"r/nhaa",
                   "controversiality":0,
                   "depth":0,
                   "author_flair_background_color":null,
                   "collapsed_because_crowd_control":null,
                   "mod_reports":[
                      
                   ],
                   "mod_note":null,
                   "distinguished":null
                }
             }
          ],
          "after":null,
          "before":null
       }
    }
 ]