export const API_DATA_TEST = {
    "kind":"Listing",
    "data":{
       "modhash":"ib31047sn8880846f195d32925dbe3a00a30c185efcf727cd4",
       "dist":25,
       "children":[
          {
             "kind":"t3",
             "data":{
                "approved_at_utc":null,
                "subreddit":"nhaa",
                "selftext":"",
                "author_fullname":"t2_7192dx3f",
                "saved":false,
                "mod_reason_title":null,
                "gilded":0,
                "clicked":false,
                "title":"Gostaram do meu trabalho",
                "link_flair_richtext":[
                   
                ],
                "subreddit_name_prefixed":"r/nhaa",
                "hidden":false,
                "pwls":6,
                "link_flair_css_class":null,
                "downs":0,
                "thumbnail_height":140,
                "top_awarded_type":null,
                "hide_score":false,
                "name":"t3_j5q1ak",
                "quarantine":false,
                "link_flair_text_color":"dark",
                "upvote_ratio":0.97,
                "author_flair_background_color":null,
                "subreddit_type":"public",
                "ups":1338,
                "total_awards_received":5,
                "media_embed":{
                   
                },
                "thumbnail_width":140,
                "author_flair_template_id":null,
                "is_original_content":false,
                "user_reports":[
                   
                ],
                "secure_media":null,
                "is_reddit_media_domain":true,
                "is_meta":false,
                "category":null,
                "secure_media_embed":{
                   
                },
                "link_flair_text":null,
                "can_mod_post":false,
                "score":1338,
                "approved_by":null,
                "author_premium":false,
                "thumbnail":"https://b.thumbs.redditmedia.com/BHjU_JCYZtd8jnTWqYcjGuDdxXtaIlzRBVJoziAUK-U.jpg",
                "edited":false,
                "author_flair_css_class":null,
                "author_flair_richtext":[
                   
                ],
                "gildings":{
                   "gid_1":1
                },
                "post_hint":"image",
                "content_categories":null,
                "is_self":false,
                "mod_note":null,
                "created":1601954811.0,
                "link_flair_type":"text",
                "wls":6,
                "removed_by_category":null,
                "banned_by":null,
                "author_flair_type":"text",
                "domain":"i.redd.it",
                "allow_live_comments":false,
                "selftext_html":null,
                "likes":null,
                "suggested_sort":null,
                "banned_at_utc":null,
                "url_overridden_by_dest":"https://i.redd.it/4p3ly6qyubr51.png",
                "view_count":null,
                "archived":false,
                "no_follow":false,
                "is_crosspostable":true,
                "pinned":false,
                "over_18":false,
                "preview":{
                   "images":[
                      {
                         "source":{
                            "url":"https://preview.redd.it/4p3ly6qyubr51.png?auto=webp&amp;s=d303f52c11e9e681b64b22ff34292256c4fea5f9",
                            "width":720,
                            "height":722
                         },
                         "resolutions":[
                            {
                               "url":"https://preview.redd.it/4p3ly6qyubr51.png?width=108&amp;crop=smart&amp;auto=webp&amp;s=7042349967422ce49e4bef2a31e35d728f013608",
                               "width":108,
                               "height":108
                            },
                            {
                               "url":"https://preview.redd.it/4p3ly6qyubr51.png?width=216&amp;crop=smart&amp;auto=webp&amp;s=b1cd669d547c47a8b0f34131bc4adae499263fdc",
                               "width":216,
                               "height":216
                            },
                            {
                               "url":"https://preview.redd.it/4p3ly6qyubr51.png?width=320&amp;crop=smart&amp;auto=webp&amp;s=e441351b40844e640f953bcb678343c37b57789a",
                               "width":320,
                               "height":320
                            },
                            {
                               "url":"https://preview.redd.it/4p3ly6qyubr51.png?width=640&amp;crop=smart&amp;auto=webp&amp;s=e74dcef84db2192759f8794f18febbd1b39dafc3",
                               "width":640,
                               "height":641
                            }
                         ],
                         "variants":{
                            
                         },
                         "id":"sRJMoZcX5cRcMNcvYs649_I9rT2lMO8vGH481z93FzM"
                      }
                   ],
                   "enabled":true
                },
                "all_awardings":[
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":150,
                      "id":"award_f44611f1-b89e-46dc-97fe-892280b13b82",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"Thank you stranger. Shows the award.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":2,
                      "static_icon_height":2048,
                      "name":"Helpful",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":2048,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png"
                   },
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":125,
                      "id":"award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"When you come across a feel-good thing.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":1,
                      "static_icon_height":2048,
                      "name":"Wholesome",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":2048,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png"
                   },
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":100,
                      "id":"gid_1",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://www.redditstatic.com/gold/awards/icon/silver_512.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":512,
                      "static_icon_width":512,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"Shows the Silver Award... and that's it.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":1,
                      "static_icon_height":512,
                      "name":"Silver",
                      "resized_static_icons":[
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":512,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://www.redditstatic.com/gold/awards/icon/silver_512.png"
                   },
                   {
                      "giver_coin_reward":0,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":80,
                      "id":"award_8352bdff-3e03-4189-8a08-82501dd8f835",
                      "penny_donate":0,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=16&amp;height=16&amp;auto=webp&amp;s=85b1aa61933f163dd2b77b1e78f4d82d9c947ec1",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=32&amp;height=32&amp;auto=webp&amp;s=67935636337b07ca5b98d945f4bcdae26e5f567e",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=48&amp;height=48&amp;auto=webp&amp;s=547d5fb33f5a4a5d6fc154cbd658638cc2b1c3a0",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=64&amp;height=64&amp;auto=webp&amp;s=e17bc331183e7ba194314a34e43b35460a835fff",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=128&amp;height=128&amp;auto=webp&amp;s=1b4e617f18af8d4e2c47c2f154d4422be43c809f",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"Everything is better with a good hug",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":1,
                      "static_icon_height":2048,
                      "name":"Hugz",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=16&amp;height=16&amp;auto=webp&amp;s=85b1aa61933f163dd2b77b1e78f4d82d9c947ec1",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=32&amp;height=32&amp;auto=webp&amp;s=67935636337b07ca5b98d945f4bcdae26e5f567e",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=48&amp;height=48&amp;auto=webp&amp;s=547d5fb33f5a4a5d6fc154cbd658638cc2b1c3a0",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=64&amp;height=64&amp;auto=webp&amp;s=e17bc331183e7ba194314a34e43b35460a835fff",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=128&amp;height=128&amp;auto=webp&amp;s=1b4e617f18af8d4e2c47c2f154d4422be43c809f",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":"PNG",
                      "icon_height":2048,
                      "penny_price":0,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png"
                   }
                ],
                "awarders":[
                   
                ],
                "media_only":false,
                "can_gild":true,
                "spoiler":false,
                "locked":false,
                "author_flair_text":null,
                "treatment_tags":[
                   
                ],
                "visited":false,
                "removed_by":null,
                "num_reports":null,
                "distinguished":null,
                "subreddit_id":"t5_qwpqj",
                "mod_reason_by":null,
                "removal_reason":null,
                "link_flair_background_color":"",
                "id":"j5q1ak",
                "is_robot_indexable":true,
                "report_reasons":null,
                "author":"pelucio2020",
                "discussion_type":null,
                "num_comments":35,
                "send_replies":true,
                "whitelist_status":"all_ads",
                "contest_mode":false,
                "mod_reports":[
                   
                ],
                "author_patreon_flair":false,
                "author_flair_text_color":null,
                "permalink":"/r/nhaa/comments/j5q1ak/gostaram_do_meu_trabalho/",
                "parent_whitelist_status":"all_ads",
                "stickied":false,
                "url":"https://i.redd.it/4p3ly6qyubr51.png",
                "subreddit_subscribers":369741,
                "created_utc":1601926011.0,
                "num_crossposts":0,
                "media":null,
                "is_video":false
             }
          },
          {
             "kind":"t3",
             "data":{
                "approved_at_utc":null,
                "subreddit":"nhaa",
                "selftext":"",
                "author_fullname":"t2_7jrlwzml",
                "saved":false,
                "mod_reason_title":null,
                "gilded":0,
                "clicked":false,
                "title":"Sempre assim",
                "link_flair_richtext":[
                   {
                      "e":"text",
                      "t":"MEME"
                   }
                ],
                "subreddit_name_prefixed":"r/nhaa",
                "hidden":false,
                "pwls":6,
                "link_flair_css_class":"",
                "downs":0,
                "thumbnail_height":140,
                "top_awarded_type":null,
                "hide_score":false,
                "name":"t3_j5p10u",
                "quarantine":false,
                "link_flair_text_color":"light",
                "upvote_ratio":0.98,
                "author_flair_background_color":null,
                "subreddit_type":"public",
                "ups":1745,
                "total_awards_received":7,
                "media_embed":{
                   
                },
                "thumbnail_width":140,
                "author_flair_template_id":null,
                "is_original_content":false,
                "user_reports":[
                   
                ],
                "secure_media":null,
                "is_reddit_media_domain":true,
                "is_meta":false,
                "category":null,
                "secure_media_embed":{
                   
                },
                "link_flair_text":"MEME",
                "can_mod_post":false,
                "score":1745,
                "approved_by":null,
                "author_premium":false,
                "thumbnail":"https://b.thumbs.redditmedia.com/4WSlOttP07GQgy-wRdwpS4vmOtV8qWi6q6ViBcxdmMg.jpg",
                "edited":false,
                "author_flair_css_class":null,
                "author_flair_richtext":[
                   
                ],
                "gildings":{
                   
                },
                "post_hint":"image",
                "content_categories":null,
                "is_self":false,
                "mod_note":null,
                "created":1601951661.0,
                "link_flair_type":"richtext",
                "wls":6,
                "removed_by_category":null,
                "banned_by":null,
                "author_flair_type":"text",
                "domain":"i.redd.it",
                "allow_live_comments":false,
                "selftext_html":null,
                "likes":null,
                "suggested_sort":null,
                "banned_at_utc":null,
                "url_overridden_by_dest":"https://i.redd.it/tvzij2qllbr51.jpg",
                "view_count":null,
                "archived":false,
                "no_follow":false,
                "is_crosspostable":true,
                "pinned":false,
                "over_18":false,
                "preview":{
                   "images":[
                      {
                         "source":{
                            "url":"https://preview.redd.it/tvzij2qllbr51.jpg?auto=webp&amp;s=1e848b0230337ab7387f1af0e5fe79011e00522a",
                            "width":720,
                            "height":753
                         },
                         "resolutions":[
                            {
                               "url":"https://preview.redd.it/tvzij2qllbr51.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=0d8081c670cc7b9837724c455dac313fbd84e19c",
                               "width":108,
                               "height":112
                            },
                            {
                               "url":"https://preview.redd.it/tvzij2qllbr51.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=e8063852f5daf8839f02676f3cd65c0ee87a735a",
                               "width":216,
                               "height":225
                            },
                            {
                               "url":"https://preview.redd.it/tvzij2qllbr51.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=33c8a2ac106f23f7b75c60d1050cc4f353fc13de",
                               "width":320,
                               "height":334
                            },
                            {
                               "url":"https://preview.redd.it/tvzij2qllbr51.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=9ba8e919a840c4fd03d119111b235b2aa02bab70",
                               "width":640,
                               "height":669
                            }
                         ],
                         "variants":{
                            
                         },
                         "id":"7KUIK4hZB1gTJHGYpF6WPBCwn-xihdzEE5OUhENOLMc"
                      }
                   ],
                   "enabled":true
                },
                "all_awardings":[
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":300,
                      "id":"award_28e8196b-d4e9-45bc-b612-cd4c7d3ed4b3",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=16&amp;height=16&amp;auto=webp&amp;s=c1400eb6ea235d0c96c3aa6e271c71d7f339cbd4",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=32&amp;height=32&amp;auto=webp&amp;s=77ad345b2f9b062140e028764394594326771a17",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=48&amp;height=48&amp;auto=webp&amp;s=5b5211166e4b260311ad9f3ea31d3b815110769c",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=64&amp;height=64&amp;auto=webp&amp;s=bf3a2c642ad50547087d770c65c29777970d3af3",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=128&amp;height=128&amp;auto=webp&amp;s=eae06d6a70c62c78dc66cb14f2a84651cb822cc4",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"When an upvote just isn't enough, smash the Rocket Like.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":1,
                      "static_icon_height":2048,
                      "name":"Rocket Like",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=16&amp;height=16&amp;auto=webp&amp;s=c1400eb6ea235d0c96c3aa6e271c71d7f339cbd4",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=32&amp;height=32&amp;auto=webp&amp;s=77ad345b2f9b062140e028764394594326771a17",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=48&amp;height=48&amp;auto=webp&amp;s=5b5211166e4b260311ad9f3ea31d3b815110769c",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=64&amp;height=64&amp;auto=webp&amp;s=bf3a2c642ad50547087d770c65c29777970d3af3",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png?width=128&amp;height=128&amp;auto=webp&amp;s=eae06d6a70c62c78dc66cb14f2a84651cb822cc4",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":2048,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/94pn64yuas941_RocketLike.png"
                   },
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":150,
                      "id":"award_f44611f1-b89e-46dc-97fe-892280b13b82",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"Thank you stranger. Shows the award.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":2,
                      "static_icon_height":2048,
                      "name":"Helpful",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":2048,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png"
                   },
                   {
                      "giver_coin_reward":null,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":125,
                      "id":"award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                      "penny_donate":null,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"When you come across a feel-good thing.",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":3,
                      "static_icon_height":2048,
                      "name":"Wholesome",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":null,
                      "icon_height":2048,
                      "penny_price":null,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png"
                   },
                   {
                      "giver_coin_reward":0,
                      "subreddit_id":null,
                      "is_new":false,
                      "days_of_drip_extension":0,
                      "coin_price":80,
                      "id":"award_8352bdff-3e03-4189-8a08-82501dd8f835",
                      "penny_donate":0,
                      "award_sub_type":"GLOBAL",
                      "coin_reward":0,
                      "icon_url":"https://i.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png",
                      "days_of_premium":0,
                      "tiers_by_required_awardings":null,
                      "resized_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=16&amp;height=16&amp;auto=webp&amp;s=85b1aa61933f163dd2b77b1e78f4d82d9c947ec1",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=32&amp;height=32&amp;auto=webp&amp;s=67935636337b07ca5b98d945f4bcdae26e5f567e",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=48&amp;height=48&amp;auto=webp&amp;s=547d5fb33f5a4a5d6fc154cbd658638cc2b1c3a0",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=64&amp;height=64&amp;auto=webp&amp;s=e17bc331183e7ba194314a34e43b35460a835fff",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=128&amp;height=128&amp;auto=webp&amp;s=1b4e617f18af8d4e2c47c2f154d4422be43c809f",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_width":2048,
                      "static_icon_width":2048,
                      "start_date":null,
                      "is_enabled":true,
                      "awardings_required_to_grant_benefits":null,
                      "description":"Everything is better with a good hug",
                      "end_date":null,
                      "subreddit_coin_reward":0,
                      "count":1,
                      "static_icon_height":2048,
                      "name":"Hugz",
                      "resized_static_icons":[
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=16&amp;height=16&amp;auto=webp&amp;s=85b1aa61933f163dd2b77b1e78f4d82d9c947ec1",
                            "width":16,
                            "height":16
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=32&amp;height=32&amp;auto=webp&amp;s=67935636337b07ca5b98d945f4bcdae26e5f567e",
                            "width":32,
                            "height":32
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=48&amp;height=48&amp;auto=webp&amp;s=547d5fb33f5a4a5d6fc154cbd658638cc2b1c3a0",
                            "width":48,
                            "height":48
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=64&amp;height=64&amp;auto=webp&amp;s=e17bc331183e7ba194314a34e43b35460a835fff",
                            "width":64,
                            "height":64
                         },
                         {
                            "url":"https://preview.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png?width=128&amp;height=128&amp;auto=webp&amp;s=1b4e617f18af8d4e2c47c2f154d4422be43c809f",
                            "width":128,
                            "height":128
                         }
                      ],
                      "icon_format":"PNG",
                      "icon_height":2048,
                      "penny_price":0,
                      "award_type":"global",
                      "static_icon_url":"https://i.redd.it/award_images/t5_22cerq/niiatoknifn51_Hugz.png"
                   }
                ],
                "awarders":[
                   
                ],
                "media_only":false,
                "link_flair_template_id":"cc3f2bcc-aecb-11e9-b329-0e18d1a68012",
                "can_gild":true,
                "spoiler":false,
                "locked":false,
                "author_flair_text":null,
                "treatment_tags":[
                   
                ],
                "visited":false,
                "removed_by":null,
                "num_reports":null,
                "distinguished":null,
                "subreddit_id":"t5_qwpqj",
                "mod_reason_by":null,
                "removal_reason":null,
                "link_flair_background_color":"#46d160",
                "id":"j5p10u",
                "is_robot_indexable":true,
                "report_reasons":null,
                "author":"Acrobatic_Bowl",
                "discussion_type":null,
                "num_comments":17,
                "send_replies":true,
                "whitelist_status":"all_ads",
                "contest_mode":false,
                "mod_reports":[
                   
                ],
                "author_patreon_flair":false,
                "author_flair_text_color":null,
                "permalink":"/r/nhaa/comments/j5p10u/sempre_assim/",
                "parent_whitelist_status":"all_ads",
                "stickied":false,
                "url":"https://i.redd.it/tvzij2qllbr51.jpg",
                "subreddit_subscribers":369741,
                "created_utc":1601922861.0,
                "num_crossposts":0,
                "media":null,
                "is_video":false
             }
          },
       ],
       "after":"t3_j5scil",
       "before":null
    }
 };